Repository WeStillDontKnowTheAlgorithmWeSawThatDay/AlgorithmStudyOfHope, pull requests merged in 2023-08, with the labels that each got.

#10 [밀리] - 3주차 제출
  시뮬레이션/BOJ_21610_마법사상어와비바라기_밀리.py
  투포인터/BOJ_21921_블로그_밀리.py
Labels: 투 포인터, 시뮬레이션

#12 [밀리] - 5주차 제출
  누적합/BOJ_20438_출석체크_밀리.py
  이진탐색/BOJ_1654_랜선자르기_밀리.py
Labels: 이진탐색, 누적합

#13 [밀리] - 6주차 제출
  DP/BOJ_14495_피보나치비스무리한수열_밀리.py
  그래프이론/BOJ_2178_미로탐색_밀리.py
  다익스트라/BOJ_1238_파티_밀리.py
  다익스트라/BOJ_18352_특정거리의도시찾기_밀리.py
Labels: DFS/BFS, 다익스트라

#14 [메리] - 6주차 제출
  그래프이론/BOJ_2178_미로탐색_메리.py
  다익스트라/BOJ_18352_특정_거리의_도시_찾기.py
Labels: DFS/BFS, 다익스트라
